Repository SOPT-all/35-APPJAM-SERVER-NAPZAKMARKET, pull requests merged in 2025-01, with the labels that each got.

#2 [feat] #1 - 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .github/relases-drafter-config.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/napjak/NapjakApplication.java
  src/main/java/com/napjak/domain/member/core/MemberEntity.java
  src/main/java/com/napjak/domain/member/core/MemberTableConstants.java
  src/main/java/com/napjak/domain/member/core/Role.java
  src/main/java/com/napjak/domain/member/core/SocialType.java
  src/main/java/com/napjak/global/auth/annotation/CurrentMember.java
  src/main/java/com/napjak/global/auth/jwt/exception/TokenErrorCode.java
  src/main/java/com/napjak/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/napjak/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/napjak/global/auth/jwt/provider/JwtValidationType.java
  src/main/java/com/napjak/global/auth/jwt/repository/TokenRepository.java
  src/main/java/com/napjak/global/auth/jwt/service/TokenService.java
  src/main/java/com/napjak/global/auth/redis/LettuceLockRepository.java
  src/main/java/com/napjak/global/auth/redis/Token.java
  src/main/java/com/napjak/global/auth/resolver/CurrentMemberArgumentResolver.java
  src/main/java/com/napjak/global/auth/security/AdminAuthentication.java
  src/main/java/com/napjak/global/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/napjak/global/auth/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/napjak/global/auth/security/MemberAuthentication.java
  src/main/java/com/napjak/global/common/api/controller/HealthCheckApi.java
  src/main/java/com/napjak/global/common/api/controller/HealthCheckController.java
  src/main/java/com/napjak/global/common/config/JpaAuditingConfig.java
  src/main/java/com/napjak/global/common/config/MysqlCustomDialect.java
  src/main/java/com/napjak/global/common/config/QueryDslConfig.java
  src/main/java/com/napjak/global/common/config/RedisConfig.java
  src/main/java/com/napjak/global/common/config/SecurityConfig.java
  src/main/java/com/napjak/global/common/config/WebConfig.java
  src/main/java/com/napjak/global/common/converter/StringToEnumCustomConverterFactory.java
  src/main/java/com/napjak/global/common/entity/BaseTimeEntity.java
  src/main/java/com/napjak/global/common/exception/NapjakException.java
  src/main/java/com/napjak/global/common/exception/base/BaseErrorCode.java
  src/main/java/com/napjak/global/common/exception/base/BaseSuccessCode.java
  src/main/java/com/napjak/global/common/exception/code/ErrorCode.java
  src/main/java/com/napjak/global/common/exception/code/SuccessCode.java
  src/main/java/com/napjak/global/common/exception/dto/ErrorResponse.java
  src/main/java/com/napjak/global/common/exception/dto/SuccessResponse.java
  src/main/java/com/napjak/global/common/handler/GlobalExceptionHandler.java
  src/main/java/com/napjak/global/external/s3/api/service/FileService.java
  src/main/java/com/napjak/global/external/s3/config/S3Config.java
  src/main/java/com/napjak/global/external/s3/exception/FileSuccessCode.java
  src/main/java/com/napjak/global/swagger/annotation/DisableSwaggerSecurity.java
  src/main/java/com/napjak/global/swagger/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/napjak/NapjakApplicationTests.java
Labels: feat 🎯, init, 혜린😼

#7 [feat] #3 - 카카오 소셜 로그인 환경 + Member 도메인 로그인 기능 구현
  src/main/java/com/napzak/NapzakApplication.java
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/AccessTokenGenerateResponse.java
  src/main/java/com/napzak/domain/store/api/dto/LoginSuccessResponse.java
  src/main/java/com/napzak/domain/store/api/dto/StoreLoginResponse.java
  src/main/java/com/napzak/domain/store/api/service/AuthenticationService.java
  src/main/java/com/napzak/domain/store/api/service/LoginService.java
  src/main/java/com/napzak/domain/store/api/service/StoreRegistrationService.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/Role.java
  src/main/java/com/napzak/domain/store/core/SocialType.java
  src/main/java/com/napzak/domain/store/core/StoreEntity.java
  src/main/java/com/napzak/domain/store/core/StoreRepository.java
  src/main/java/com/napzak/domain/store/core/StoreTableConstants.java
  src/main/java/com/napzak/domain/store/core/exception/StoreErrorCode.java
  src/main/java/com/napzak/domain/store/core/exception/StoreSuccessCode.java
  src/main/java/com/napzak/global/auth/client/dto/StoreLoginRequest.java
  src/main/java/com/napzak/global/auth/client/dto/StoreSocialInfoResponse.java
  src/main/java/com/napzak/global/auth/client/kakao/KakaoApiClient.java
  src/main/java/com/napzak/global/auth/client/kakao/KakaoAuthApiClient.java
  src/main/java/com/napzak/global/auth/client/kakao/dto/KakaoAccessTokenResponse.java
  src/main/java/com/napzak/global/auth/client/kakao/dto/KakaoUserResponse.java
  src/main/java/com/napzak/global/auth/client/service/KakaoSocialService.java
  src/main/java/com/napzak/global/auth/client/service/SocialService.java
  src/main/java/com/napzak/global/auth/jwt/exception/TokenErrorCode.java
  src/main/java/com/napzak/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/napzak/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/napzak/global/auth/jwt/service/TokenService.java
  src/main/java/com/napzak/global/auth/security/MemberAuthentication.java
  src/main/java/com/napzak/global/common/config/SecurityConfig.java
Labels: feat 🎯, 세희🐰

#10 [#8] feat - CI/CD 구성
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
  .github/workflows/release-drafter.yml
  Dockerfile-dev
  Dockerfile-prod
  docker-compose-dev.yml
  docker-compose-prod.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat 🎯, deploy 🚀, 혜린😼

#11 [feat] #8 - Dockerfile 수정
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, deploy 🚀, 혜린😼

#13 [fix] #12 - workflow 수정
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: fix 🛠️, deploy 🚀, 혜린😼

#16 [fix] #15 - cd env 지정
  .github/workflows/dev-CD.yml
  .github/workflows/prod-CD.yml
Labels: fix 🛠️, 혜린😼

#18 [fix] #17 - dev-CD 환경변수 이름 수정
  .github/workflows/dev-CD.yml
Labels: fix 🛠️, 혜린😼

#22 [refactor] #21 - Dockerfile 명령어 수정
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, 혜린😼

#27 [refactor] #25 - 명령어 오타 수정
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, 혜린😼

#29 [fix] #28 - jar 파일 이름 변경
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, 혜린😼

#30 [fix] #28 - jar 파일 이름 변경
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, 혜린😼

#32 [refactor] #31 - 배포 방식 변경
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: refactor 🔁, 혜린😼

#33 [refactor] #31 - docker-compose 지정
  .github/workflows/dev-CD.yml
  .github/workflows/prod-CD.yml
Labels: fix 🛠️, 혜린😼

#37 [refactor] #36 - deploy.sh 추가
  .github/workflows/dev-CD.yml
  .github/workflows/prod-CD.yml
Labels: refactor 🔁, 혜린😼

#39 [fix] #38 - docker-compose 변경
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CI.yml
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: fix 🛠️, 혜린😼

#43 [refactor] #42 - CICD 실행 조건 구체화
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: refactor 🔁, 혜린😼

#44 [refactor] #42 - cicd trigger 양식 수정
  .github/workflows/prod-CD.yml
Labels: refactor 🔁, 혜린😼

#47 [deploy] CI/CD 수정 테스트
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
Labels: deploy 🚀, 혜린😼

#51 [#50] fix: 엔티티 수정
  src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductPhotoEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductTableConstants.java
  src/main/java/com/napzak/domain/product/core/vo/Product.java
  src/main/java/com/napzak/domain/store/core/entity/StoreEntity.java
Labels: fix 🛠️, 세희🐰

#65 [feat] #49 - 탐색탭 api 구현
  docker-compose-dev.yml
  docker-compose-prod.yml
  src/main/java/com/napzak/domain/genre/core/GenreRepository.java
  src/main/java/com/napzak/domain/genre/core/GenreRetriever.java
  src/main/java/com/napzak/domain/interest/core/InterestRepository.java
  src/main/java/com/napzak/domain/interest/core/InterestRetriever.java
  src/main/java/com/napzak/domain/interest/core/entity/InterestEntity.java
  src/main/java/com/napzak/domain/interest/core/vo/Interest.java
  src/main/java/com/napzak/domain/product/api/ProductGenreFacade.java
  src/main/java/com/napzak/domain/product/api/ProductInterestFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/request/cursor/Cursor.java
  src/main/java/com/napzak/domain/product/api/dto/request/cursor/HighPriceCursor.java
  src/main/java/com/napzak/domain/product/api/dto/request/cursor/LowPriceCursor.java
  src/main/java/com/napzak/domain/product/api/dto/request/cursor/PopularCursor.java
  src/main/java/com/napzak/domain/product/api/dto/request/cursor/RecentCursor.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java
  src/main/java/com/napzak/domain/product/api/exception/ProductErrorCode.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductPagination.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/api/service/enums/SortOption.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRepository.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRetriever.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductTableConstants.java
  src/main/java/com/napzak/domain/product/core/vo/Product.java
  src/main/java/com/napzak/domain/product/core/vo/ProductWithFirstPhoto.java
  src/main/java/com/napzak/domain/product/core/vo/ProductWithFirstPhotoList.java
  src/main/java/com/napzak/global/common/util/TimeUtils.java
Labels: feat 🎯, 혜린😼

#61 [refactor] #60 - 각 테이블 pk column명 변경
  src/main/java/com/napzak/domain/banner/core/entity/BannerTableConstants.java
  src/main/java/com/napzak/domain/chat/core/entity/ChatMessageTableConstants.java
  src/main/java/com/napzak/domain/chat/core/entity/ChatRoomTableConstants.java
  src/main/java/com/napzak/domain/genre/core/entity/GenreTableConstants.java
  src/main/java/com/napzak/domain/interest/core/entity/InterestTableConstants.java
  src/main/java/com/napzak/domain/product/core/entity/HashtagTableConstants.java
  src/main/java/com/napzak/domain/product/core/entity/ProductHashtagTableConstants.java
  src/main/java/com/napzak/domain/product/core/entity/ProductPhotoTableConstants.java
  src/main/java/com/napzak/domain/review/core/entity/ReviewTableConstants.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/core/entity/GenrePreferenceTableConstants.java
Labels: refactor 🔁, 세희🐰

#67 [feat] #66 - 상점 상품 조회 api 구현 및 상품주인여부 반환 로직 추가
  src/main/java/com/napzak/domain/interest/core/InterestRepository.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/product/core/vo/ProductWithFirstPhoto.java
Labels: feat 🎯, 혜린😼

#69 [refactor] #68 - 엔티티 연관관계 제거
  src/main/java/com/napzak/domain/chat/core/entity/ChatMessageEntity.java
  src/main/java/com/napzak/domain/chat/core/entity/ChatRoomEntity.java
  src/main/java/com/napzak/domain/chat/core/vo/ChatMessage.java
  src/main/java/com/napzak/domain/chat/core/vo/ChatRoom.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRepository.java
  src/main/java/com/napzak/domain/product/core/entity/ProductHashtagEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductPhotoEntity.java
  src/main/java/com/napzak/domain/product/core/vo/ProductHashtag.java
  src/main/java/com/napzak/domain/product/core/vo/ProductPhoto.java
  src/main/java/com/napzak/domain/review/core/entity/ReviewEntity.java
  src/main/java/com/napzak/domain/review/core/vo/Review.java
  src/main/java/com/napzak/domain/store/core/entity/GenrePreferenceEntity.java
  src/main/java/com/napzak/domain/store/core/vo/GenrePreference.java
Labels: refactor 🔁, 혜린😼

#74 [feat] #72 - 상품 등록 관련 api 구현
  src/main/java/com/napzak/domain/interest/core/entity/InterestEntity.java
  src/main/java/com/napzak/domain/product/api/annotation/SequenceValidator.java
  src/main/java/com/napzak/domain/product/api/annotation/ValidSequence.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/request/ProductBuyCreateRequest.java
  src/main/java/com/napzak/domain/product/api/dto/request/ProductPhotoRequestDto.java
  src/main/java/com/napzak/domain/product/api/dto/request/ProductSellCreateRequest.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductPhotoResponseDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellResponse.java
  src/main/java/com/napzak/domain/product/api/exception/ProductErrorCode.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoSaver.java
  src/main/java/com/napzak/domain/product/core/ProductSaver.java
  src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductPhotoEntity.java
  src/main/java/com/napzak/global/common/annotation/EnumValidator.java
  src/main/java/com/napzak/global/common/annotation/ValidEnum.java
  src/main/java/com/napzak/global/external/s3/api/controller/FileController.java
  src/main/java/com/napzak/global/external/s3/api/dto/ProductPresignedUrlFindAllResponse.java
  src/main/java/com/napzak/global/external/s3/api/service/FileService.java
Labels: feat 🎯, 혜린😼

#81 [#80] refactor - StoreController request 정의 및 검증 추가
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
Labels: refactor 🔁, 혜린😼

#83 [fix] #82 - CD 이슈 해결
  .dockerignore
  .github/workflows/dev-CD.yml
  .github/workflows/prod-CD.yml
  Dockerfile-dev
  Dockerfile-prod
Labels: fix 🛠️, 혜린😼

#84 [fix] #82 - cd 이슈 해결
  .dockerignore
  .github/workflows/dev-CD.yml
  Dockerfile-dev
Labels: fix 🛠️, 혜린😼

#90 [fix] #89 - docker-compose redis 관련 설정 변경
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: fix 🛠️, 혜린😼

#92 [fix] #91 - yml 주입 관련 수정
  .github/workflows/dev-CD.yml
  Dockerfile-dev
Labels: fix 🛠️, 혜린😼

#76 [feat] #73 - 홈 화면 정보 반환
  src/main/java/com/napzak/domain/banner/api/controller/BannerController.java
  src/main/java/com/napzak/domain/banner/api/dto/response/HomeBannerResponse.java
  src/main/java/com/napzak/domain/banner/api/exception/BannerSuccessCode.java
  src/main/java/com/napzak/domain/banner/api/service/BannerService.java
  src/main/java/com/napzak/domain/banner/core/BannerRepository.java
  src/main/java/com/napzak/domain/banner/core/BannerRetriever.java
  src/main/java/com/napzak/domain/product/api/ProductStoreFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java
  src/main/java/com/napzak/domain/product/api/exception/ProductErrorCode.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/store/api/dto/GenrePreferenceResponse.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRepository.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRetriever.java
Labels: feat 🎯, 세희🐰

#97 [refactor] #96 - entity 설정 변경
  src/main/java/com/napzak/domain/banner/core/entity/BannerEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
  src/main/java/com/napzak/domain/review/core/entity/ReviewEntity.java
  src/main/java/com/napzak/domain/store/api/service/StoreRegistrationService.java
  src/main/java/com/napzak/domain/store/core/StoreSaver.java
  src/main/java/com/napzak/domain/store/core/entity/StoreEntity.java
  src/main/java/com/napzak/domain/store/core/entity/StoreTableConstants.java
  src/main/java/com/napzak/domain/store/core/vo/Store.java
Labels: refactor 🔁, 세희🐰

#99 [chore] #98 - 명세 반영한 소소한 수정
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/global/common/config/SecurityConfig.java
Labels: chore 🔍, 혜린😼

#101 [fix] #100 - banner를 list로 수정하도록 변경
  src/main/java/com/napzak/domain/banner/api/controller/BannerController.java
  src/main/java/com/napzak/domain/banner/api/dto/response/BannerResponseList.java
Labels: refactor 🔁, 세희🐰

#103 [fix] #102 - default genre id 변경
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
Labels: fix 🛠️, 세희🐰

#105 [fix] #104 - 사용하는 dto 변경
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
Labels: fix 🛠️, 세희🐰

#77 [feat] #74 - 마이페이지, 상점 정보 조회 api 구현
  src/main/java/com/napzak/domain/store/api/StoreGenreFacade.java
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/GenrePreferenceDto.java
  src/main/java/com/napzak/domain/store/api/dto/GenrePreferenceResponse.java
  src/main/java/com/napzak/domain/store/api/dto/MyPageResponse.java
  src/main/java/com/napzak/domain/store/api/dto/StoreInfoResponse.java
  src/main/java/com/napzak/domain/store/api/exception/StoreErrorCode.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRepository.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
Labels: feat 🎯, 세희🐰

#79 [feat] #78 - 좋아요, 좋아요 해제 기능 구현
  src/main/java/com/napzak/domain/interest/api/InterestProductFacade.java
  src/main/java/com/napzak/domain/interest/api/controller/InterestController.java
  src/main/java/com/napzak/domain/interest/api/exception/InterestErrorCode.java
  src/main/java/com/napzak/domain/interest/api/exception/InterestSuccessCode.java
  src/main/java/com/napzak/domain/interest/api/service/InterestService.java
  src/main/java/com/napzak/domain/interest/core/InterestRemover.java
  src/main/java/com/napzak/domain/interest/core/InterestSaver.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/product/core/ProductUpdater.java
Labels: feat 🎯, 세희🐰

#107 [feat] #106 - 장르 이름 조회 api 구현
  src/main/java/com/napzak/domain/genre/api/controller/GenreController.java
Labels: feat 🎯, 혜린😼

#110 [feat] #108 - 채팅관련 상품 정보 조회 api 구현
  src/main/java/com/napzak/domain/product/api/ProductStoreFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductChatResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRepository.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRetriever.java
  src/main/java/com/napzak/domain/store/core/StoreRepository.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
Labels: feat 🎯, 혜린😼

#111 [comment] #109 - 로그 확인용 코드
  src/main/java/com/napzak/domain/interest/api/controller/InterestController.java
  src/main/java/com/napzak/domain/interest/api/service/InterestService.java
  src/main/java/com/napzak/domain/interest/core/entity/InterestEntity.java
Labels: fix 🛠️, 세희🐰

#87 [feat] #53 - 상품 상세 정보 조회 api
  src/main/java/com/napzak/domain/product/api/ProductGenreFacade.java
  src/main/java/com/napzak/domain/product/api/ProductReviewFacade.java
  src/main/java/com/napzak/domain/product/api/ProductStoreFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductPhotoDto.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/review/api/dto/response/StoreReviewDto.java
  src/main/java/com/napzak/domain/review/api/exception/ReviewErrorCode.java
  src/main/java/com/napzak/domain/review/core/ReviewRepository.java
  src/main/java/com/napzak/domain/review/core/ReviewRetriever.java
  src/main/java/com/napzak/domain/store/api/dto/StoreStatusDto.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/StoreRepository.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
Labels: feat 🎯, 세희🐰

#114 [#113] feat(ProductDetailDto): productCondition null 체크 추가 및 null일 경우…
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailDto.java
Labels: fix 🛠️, 혜린😼

#116 [feat #112 - swagger 문서화
  src/main/java/com/napzak/domain/banner/api/controller/BannerApi.java
  src/main/java/com/napzak/domain/banner/api/controller/BannerController.java
  src/main/java/com/napzak/domain/genre/api/controller/GenreApi.java
  src/main/java/com/napzak/domain/genre/api/controller/GenreController.java
  src/main/java/com/napzak/domain/interest/api/controller/InterestApi.java
  src/main/java/com/napzak/domain/interest/api/controller/InterestController.java
  src/main/java/com/napzak/domain/product/api/controller/ProductApi.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/global/external/s3/api/controller/FileApi.java
  src/main/java/com/napzak/global/external/s3/api/controller/FileController.java
Labels: feat 🎯, 혜린😼

#120 [chore] #118 - ProductDetailDto 반환 필드명 수정
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailDto.java
Labels: chore 🔍, 혜린😼

#122 [fix] #121 - 홈화면 추천 상품 이슈
  src/main/java/com/napzak/domain/product/api/controller/ProductApi.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductRecommendListResponse.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
Labels: fix 🛠️, 혜린😼

#124 [feat] #123 - swagger 문서화 보강
  src/main/java/com/napzak/domain/product/api/controller/ProductApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
Labels: feat 🎯, 혜린😼

#126 [refactor] #125 - 검색결과 없을 시 빈 리스트 반환하도록 수정
  src/main/java/com/napzak/domain/genre/api/service/GenrePagination.java
  src/main/java/com/napzak/domain/product/api/service/ProductPagination.java
Labels: refactor 🔁, 혜린😼

#128 [chore] #127 - error, success코드 주석 형식 맞춤
  src/main/java/com/napzak/domain/banner/api/exception/BannerSuccessCode.java
  src/main/java/com/napzak/domain/interest/api/exception/InterestErrorCode.java
  src/main/java/com/napzak/domain/interest/api/exception/InterestSuccessCode.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/review/api/exception/ReviewErrorCode.java
  src/main/java/com/napzak/domain/store/api/exception/StoreErrorCode.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
Labels: chore 🔍, 세희🐰

#132 [fix] #130 - storeNickname -> storeNickName
  src/main/java/com/napzak/domain/store/api/dto/MyPageResponse.java
Labels: fix 🛠️, 세희🐰

#134 [chore] #133 - 패키지 분리, store controller 리팩토링
  src/main/java/com/napzak/domain/product/api/ProductStoreFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailResponse.java
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/AccessTokenGenerateResponse.java
  src/main/java/com/napzak/domain/store/api/dto/GenrePreferenceDto.java
  src/main/java/com/napzak/domain/store/api/dto/LoginSuccessResponse.java
  src/main/java/com/napzak/domain/store/api/dto/StoreLoginResponse.java
  src/main/java/com/napzak/domain/store/api/dto/request/GenrePreferenceRequest.java
  src/main/java/com/napzak/domain/store/api/dto/response/AccessTokenGenerateResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/LoginSuccessResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/MyPageResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreInfoResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreLoginResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreStatusDto.java
  src/main/java/com/napzak/domain/store/api/service/AuthenticationService.java
  src/main/java/com/napzak/domain/store/api/service/LoginService.java
  src/main/java/com/napzak/domain/store/core/StoreRepository.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
Labels: refactor 🔁, chore 🔍, 세희🐰

#136 [feat] #135 - AOP 적용 및 api별 쿼리 개수 추적
  build.gradle
  src/main/java/com/napzak/global/common/annotation/QueryLoggingAspect.java
  src/main/java/com/napzak/global/common/config/HibernateConfig.java
  src/main/java/com/napzak/global/common/config/LoggingFilter.java
  src/main/java/com/napzak/global/common/config/QueryInspector.java
  src/main/java/com/napzak/global/common/util/QueryCounter.java
Labels: feat 🎯, 혜린😼

#140 [refactor] #139 - 사용하지 않는 코드 삭제
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRetriever.java
Labels: refactor 🔁, 세희🐰

#138 [refactor] #137 - 선호장르 등록 api 호출 쿼리 수 개선
  src/main/java/com/napzak/domain/genre/core/GenreRepository.java
  src/main/java/com/napzak/domain/genre/core/GenreRetriever.java
  src/main/java/com/napzak/domain/store/api/StoreGenreFacade.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/service/StoreRegistrationService.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRepository.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRepositoryCustom.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceSaver.java
Labels: refactor 🔁, 세희🐰

#142 [feat] #141 - AOP transaction 범위 추적
  src/main/java/com/napzak/domain/product/core/ProductPhotoSaver.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/product/core/ProductSaver.java
  src/main/java/com/napzak/domain/store/core/GenrePreferenceRetriever.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
  src/main/java/com/napzak/global/common/annotation/TransactionMonitoringAspect.java
Labels: feat 🎯, 혜린😼
